-- AlterTable
ALTER TABLE `Notification` MODIFY `kind` ENUM('TASK_ASSIGNED', 'TASK_REASSIGNED', 'TASK_UNASSIGNED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'TASK_CANCELLED', 'TASK_UPDATED', 'TASK_SUBMITTED', 'TASK_COMMENT', 'DAILY_SUMMARY', 'GENERIC') NOT NULL;
